// Generated by CoffeeScript 1.4.0
(function() {
  var $, Application, EventEmitter, History, Request, Router, Validator, aryToObj, defaultOptions, errorlet, isFunction, loglet, util, _,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __slice = [].slice;

  Router = require('./router');

  Request = require('./request');

  $ = require('jquery');

  require('bootstrap');

  loglet = require('loglet');

  util = require('./util');

  errorlet = require('errorlet');

  _ = require('underscore');

  History = require('./history');

  Validator = require('checklet');

  EventEmitter = require('events').EventEmitter;

  isFunction = function(o) {
    return typeof o === 'function' || o instanceof Function;
  };

  aryToObj = function(ary, obj) {
    var name, value, _i, _len, _ref;
    if (obj == null) {
      obj = {};
    }
    for (_i = 0, _len = ary.length; _i < _len; _i++) {
      _ref = ary[_i], name = _ref.name, value = _ref.value;
      if (obj.hasOwnProperty(name)) {
        if (obj[name] instanceof Array) {
          obj[name].push(value);
        } else {
          obj[name] = [obj[name], value];
        }
      } else {
        obj[name] = value;
      }
    }
    return obj;
  };

  $.fn.formValue = function(evt) {
    var obj;
    if (evt == null) {
      evt = {};
    }
    obj = aryToObj($(this).serializeArray());
    loglet.log('form.Value', evt);
    if (evt.hasOwnProperty('target')) {
      obj[evt.target.name] = evt.target.value;
    }
    return obj;
  };

  defaultOptions = {
    pageID: '#main',
    modalID: '#myModal',
    stateKeys: {
      "continue": '*cnt',
      layout: '*l'
    },
    everyReq: {}
  };

  Application = (function(_super) {

    __extends(Application, _super);

    Application.Router = Router;

    Application.Validator = Validator;

    Application.create = function(options) {
      if (options == null) {
        options = {};
      }
      return new this(options);
    };

    function Application(options) {
      var _base;
      if (options == null) {
        options = {};
      }
      this.options = _.extend({}, defaultOptions, options);
      this.$ = $;
      this.location = util.parse(window.location.href);
      this.router = new Router();
      (_base = this.options).modalID || (_base.modalID = '#myModal');
      this.pageMode = 'page';
    }

    Application.prototype.initialize = function(options, cb) {
      var app;
      app = this;
      $ = app.$;
      $(function() {
        app.history = new History($, app.location.path);
        app.initializeWidgets();
        $(document).on('inserted', function(evt, res, options) {
          if (options == null) {
            options = {};
          }
          app.initializeWidgets(res.elements);
          if (options.url) {
            app.history.pushStateIf(options, null, options.url, res.request.popState);
          }
          return false;
        }).on('submit', 'form', function(evt) {
          app.onFormSubmit(this, evt);
          return false;
        }).on('click', 'a', function(evt) {
          var href, req, _ref;
          if ((_ref = $(this).attr('href')) === '#' || _ref === '' || _ref === (void 0) || _ref === null) {
            return false;
          }
          href = util.parse($(this).prop('href'));
          if (app.isExternalURL(href)) {
            window.open(href.href, '_blank');
            return false;
          } else if (href.protocol === 'javascript:') {
            return true;
          } else if ($(this).attr('download')) {
            return true;
          } else {
            req = Request.fromAnchor(this, evt, app);
            app.dispatch(req);
            return false;
          }
        });
        app.history.on('popstate', function(evt) {
          var req;
          loglet.log('window.popState', evt);
          req = Request.fromPopState(evt, app);
          return app.dispatch(req);
        });
        if (isFunction(cb)) {
          return cb(app);
        }
      });
      return app;
    };

    Application.prototype._add = function(verb, routePath, middlewares, handle) {
      if (typeof routePath !== 'string') {
        this._add(verb, '/', [routePath].concat(middlewares), handle);
      } else {
        this.router._add(verb, routePath, middlewares, handle);
      }
      return this;
    };

    Application.prototype.use = function() {
      var handle, middlewares, routePath, _i;
      routePath = arguments[0], middlewares = 3 <= arguments.length ? __slice.call(arguments, 1, _i = arguments.length - 1) : (_i = 1, []), handle = arguments[_i++];
      return this._add(/^.+$/, routePath, middlewares, handle);
    };

    Application.prototype.get = function() {
      var handle, middlewares, routePath, _i;
      routePath = arguments[0], middlewares = 3 <= arguments.length ? __slice.call(arguments, 1, _i = arguments.length - 1) : (_i = 1, []), handle = arguments[_i++];
      return this._add(/^get$/, routePath, middlewares, handle);
    };

    Application.prototype.post = function() {
      var handle, middlewares, routePath, _i;
      routePath = arguments[0], middlewares = 3 <= arguments.length ? __slice.call(arguments, 1, _i = arguments.length - 1) : (_i = 1, []), handle = arguments[_i++];
      return this._add(/^post$/, routePath, middlewares, handle);
    };

    Application.prototype.put = function() {
      var handle, middlewares, routePath, _i;
      routePath = arguments[0], middlewares = 3 <= arguments.length ? __slice.call(arguments, 1, _i = arguments.length - 1) : (_i = 1, []), handle = arguments[_i++];
      return this._add(/^put$/, routePath, middlewares, handle);
    };

    Application.prototype["delete"] = function() {
      var handle, middlewares, routePath, _i;
      routePath = arguments[0], middlewares = 3 <= arguments.length ? __slice.call(arguments, 1, _i = arguments.length - 1) : (_i = 1, []), handle = arguments[_i++];
      return this._add(/^delete$/, routePath, middlewares, handle);
    };

    Application.prototype.dispatch = function(req, cb) {
      if (cb == null) {
        cb = function() {};
      }
      if (typeof req === 'string') {
        req = Request.fromURL(req, this);
      }
      return this.router.dispatch(req, cb);
    };

    Application.prototype.initializeWidgets = function(elts) {
      if (elts == null) {
        elts = this.$(document);
      }
      this.initializeForms(elts);
      return this.initializeAnchors(elts);
    };

    Application.prototype.initializeForms = function(elts) {
      var app;
      app = this;
      return elts.find('form').each(function(i, form) {
        return app.bindForm(form);
      });
    };

    Application.prototype.bindForm = function(form) {
      var app, bindElement, elt, formValidator, obj, _i, _len, _ref;
      app = this;
      $ = this.$;
      obj = {};
      bindElement = function(elt) {
        var validator;
        if ($(elt).data('validate')) {
          validator = Validator.make($(elt).data('validate'));
          validator.on('validate-error', function(err) {
            return app.emit('validate-error', elt, err);
          });
          $(elt).on('blur', function(evt) {
            return validator.validate($(elt).val());
          });
          return obj[$(elt).prop('name')] = validator;
        }
      };
      _ref = form.elements;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        elt = _ref[_i];
        bindElement(elt);
      }
      formValidator = Validator.make({
        object: obj
      });
      formValidator.on('validate-error', function(err) {
        return app.raiseFormError(form, err);
      });
      return $(form).data('_validator', formValidator);
    };

    Application.prototype.onFormSubmit = function(form, evt) {
      var app, data, validator,
        _this = this;
      try {
        app = this;
        $ = this.$;
        validator = $(form).data('_validator');
        data = $(form).formValue(evt);
        loglet.log('onFormSubmit', form, evt, data);
        return validator.async(data, function(err) {
          var req;
          try {
            if (err) {
              return app.raiseFormError(form, err);
            } else {
              req = Request.fromForm(form, evt, app);
              loglet.log('onFormSubmit.OK', req, evt);
              return app.dispatch(req);
            }
          } catch (e) {
            return loglet.error('onFormSubmit.dispatch.error', e);
          }
        });
      } catch (e) {
        return loglet.error(e);
      }
    };

    Application.prototype.raiseFormError = function(form, err) {
      var elt, error, key, _ref, _results;
      _ref = err.errors || {};
      _results = [];
      for (key in _ref) {
        error = _ref[key];
        elt = form.elements[key];
        if (elt) {
          _results.push(this.emit('validate-error', elt, error));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    Application.prototype.isExternalURL = function(href) {
      var parsed;
      parsed = href instanceof Object ? href : util.parse(href);
      if (parsed.protocol === 'javascript:') {
        return false;
      } else {
        return this.location.host !== parsed.host;
      }
    };

    Application.prototype.initializeAnchors = function(elts) {
      var app;
      app = this;
      return elts.find('a').each(function(i, anchor) {
        if (app.isExternalURL(app.$(anchor).prop('href'))) {
          return $(anchor).addClass('external');
        }
      });
      /*
            .on 'click', (evt) ->
              loglet.log 'a.click', @, app.isExternalURL $(@).prop('href')
              if app.isExternalURL $(@).prop('href')
                window.open $(@).prop('href'), '_blank'
                false
              else
                req = Request.fromAnchor @, evt, app
                app.dispatch req
                false
      */

    };

    Application.prototype.normalizeData = function(data) {
      var state;
      if (data == null) {
        data = {};
      }
      state = {};
      state[this.options.stateKeys.layout] = false;
      data = _.extend({}, this.options.everyReq || {}, state, data);
      return data;
    };

    Application.prototype.setPageMode = function(mode, modalID) {
      if (modalID == null) {
        modalID = this.options.modalID;
      }
      $ = this.$;
      this.pageMode = mode;
      if (this.pageMode === 'modal') {
        return $(modalID).modal({
          show: true,
          keyboard: true,
          backdrop: true
        });
      } else {
        return $(modalID).modal('hide');
      }
    };

    return Application;

  })(EventEmitter);

  module.exports = Application;

}).call(this);
