// Generated by CoffeeScript 1.4.0
(function() {
  var Response, errorlet, loglet, util, _;

  loglet = require('loglet');

  _ = require('underscore');

  util = require('./util');

  errorlet = require('errorlet');

  Response = (function() {

    Response.create = function(req, xhr, data) {
      var status;
      status = xhr.status;
      if (xhr.status < 400) {
        return this.createSuccess(req, xhr, data);
      } else {
        return this.createError(req, xhr, data);
      }
    };

    Response.createSuccess = function(req, xhr, data) {
      var $, contentType, uri;
      $ = req.app.$;
      contentType = xhr.getResponseHeader('Content-Type');
      uri = xhr.getResponseHeader('X-URL');
      if (contentType.match(/^text\/html/i)) {
        return new this({
          elements: $(data),
          request: req,
          url: uri
        });
      } else if (contentType.match(/^application\/json/i)) {
        return new this({
          data: JSON.parse(data),
          request: req,
          url: uri
        });
      } else {
        throw errorlet.create({
          error: 'unknown_data_type',
          contentType: contentType,
          url: uri,
          data: data
        });
      }
    };

    Response.createError = function(req, xhr, data) {
      var contentType, error, key, obj, val;
      contentType = xhr.getResponseHeader('Content-Type');
      error = errorlet.create({
        error: 'http_response_error',
        statusCode: xhr.status
      });
      if (contentType.match(/^application\/json/i)) {
        try {
          obj = JSON.parse(data);
          for (key in obj) {
            val = obj[key];
            error[key] = val;
          }
          return new this({
            error: error,
            request: req
          });
        } catch (e) {
          return error.data = data;
        }
      } else if (contentType.match(/^text\/html/i)) {
        return new this({
          error: error,
          elements: $(data),
          request: req
        });
      } else {
        return new this({
          error: error,
          request: req
        });
      }
    };

    function Response(options) {
      this.options = options;
      _.extend(this, this.options);
      this.url = this.normalizeURL(this.url);
    }

    Response.prototype.normalizeURL = function(uri) {
      var parsed;
      parsed = util.parse(uri);
      delete parsed.query[this.request.app.options.stateKeys.layout];
      return util.stringify(parsed);
    };

    Response.prototype.render = function() {
      if (this.request.properties.hasOwnProperty('modal')) {
        return this.modal(this.request.properties.modal);
      } else {
        return this.page();
      }
    };

    Response.prototype.modal = function(modalID) {
      var $, app;
      if (modalID == null) {
        modalID = this.request.app.options.modalID;
      }
      app = this.request.app;
      $ = app.$;
      if (!this.elements) {
        throw errorlet.create({
          error: 'modal_not_a_visual_response'
        });
      } else {
        $(modalID).modal({
          backdrop: true,
          keyboard: true,
          show: true
        });
        $("" + modalID + " .modal-body .te").empty().append(this.elements).trigger('inserted', this);
        return $("" + modalID + " .modal-title").empty().text($("" + modalID + " title").text());
      }
    };

    Response.prototype.redirect = function(uri, data) {
      var parsed;
      if (data == null) {
        data = {};
      }
      parsed = util.parse(uri);
      _.extend(parsed.query, data);
      return this.request.app.dispatch(util.stringify(parsed));
    };

    Response.prototype.page = function() {
      var $, app, pageID,
        _this = this;
      app = this.request.app;
      $ = app.$;
      pageID = app.options.pageID;
      return $(pageID).fadeOut('slow', function() {
        return $(pageID).empty().append(_this.elements).fadeIn('slow').trigger('inserted', [
          _this, {
            url: _this.url,
            page: pageID
          }
        ]);
      });
    };

    return Response;

  })();

  module.exports = Response;

}).call(this);
