// Generated by CoffeeScript 1.4.0
(function() {
  var Route, loglet, pathToRegExp;

  pathToRegExp = require('path-to-regexp');

  loglet = require('loglet');

  Route = (function() {

    function Route(path) {
      this.path = path;
      this.keys = [];
      this.regex = pathToRegExp(this.path, this.keys);
    }

    Route.prototype.match = function(url) {
      var result;
      if (this.path === '/') {
        return {};
      }
      result = this.regex.exec(url);
      if (result instanceof Array) {
        return this.mapParams(result);
      } else {
        return result;
      }
    };

    Route.prototype.mapParams = function(result) {
      var i, params, _i, _ref;
      params = {};
      for (i = _i = 1, _ref = result.length; 1 <= _ref ? _i < _ref : _i > _ref; i = 1 <= _ref ? ++_i : --_i) {
        params[this.keys[i - 1].name] = result[i];
      }
      return params;
    };

    return Route;

  })();

  module.exports = Route;

}).call(this);
