// Generated by CoffeeScript 1.4.0
(function() {
  var Buffer, EventEmitter, process;

  EventEmitter = require('events').EventEmitter;

  process = require('process');

  Buffer = require('buffer');

}).call(this);
